# Generated by Django 4.1.1 on 2022-10-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user_id",
            new_name="user",
        ),
    ]
